### ISSUE TITLE
Error while adding a new order

### ISSUE THREAD

**Issue by Vek0n** [Vek0n/Korona-Zakupy-WebAPI#1]
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at KoronaZakupy.Repositories.OrdersRepository.AddRelationAsync(Int64 orderId, String userId) in /Users/szymonkaczmarek/Projects/KoronaZakupy/KoronaZakupy/Repositories/OrdersRepository.cs:line 33...

Problem with Order ID

**Comment by kivix221** [comment]
fixed. See 
f3fe868
