### ISSUE TITLE
Accepting order bug

### ISSUE THREAD

**Issue by Vek0n** [Vek0n/Korona-Zakupy-WebAPI#3]
In `CompleteOrderDTO.cs` when order is active, `List<UserDTO> UsersInfo` contains one `UserDTO` element:
`UsersInfo[0]` - person in quarantine

When volunteer accepts given order **his info is saved in position 0** of  `List<UserDTO> UsersInfo`:
`UserInfo[0]` - volunteer
`UserInfo[1]` - person in quarantine

Should be other way around

**Comment by kivix221** [comment]
This is not bug

**Comment by kivix221** [comment]
Fixed; see commit  0e027b4a8d4e994dfa946c5def64cfe9b28010e6
